name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: client/package-lock.json
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm i
      - name: Check Formatting
        run: npm run format-check